apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go9524github
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go9524github 
  name: go9524github
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go9524github
    weight: 100 
